#!/usr/bin/env node

/**
 * Generates public/firebase-messaging-sw.js at build time
 * using environment variables instead of hardcoded Firebase config.
 *
 * Run: node scripts/generate-sw.js
 * Called automatically via the "prebuild" npm script.
 */

const fs = require('fs')
const path = require('path')

// Load .env.local if present (for local dev)
try {
  const envPath = path.resolve(__dirname, '..', '.env.local')
  const envContent = fs.readFileSync(envPath, 'utf8')
  for (const line of envContent.split('\n')) {
    const match = line.match(/^([^#=]+)=(.*)$/)
    if (match && !process.env[match[1].trim()]) {
      process.env[match[1].trim()] = match[2].trim()
    }
  }
} catch {
  // .env.local may not exist in CI — env vars should be set directly
}

const config = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '',
}

const sw = `/* eslint-disable no-undef */
// Firebase Cloud Messaging service worker for background push notifications.
// Must use compat SDK — service workers cannot use ES modules.
// AUTO-GENERATED by scripts/generate-sw.js — do not edit directly.

importScripts('https://www.gstatic.com/firebasejs/12.10.0/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/12.10.0/firebase-messaging-compat.js')

firebase.initializeApp(${JSON.stringify(config, null, 2)})

const messaging = firebase.messaging()

messaging.onBackgroundMessage((payload) => {
  const { title, body, url } = payload.data || {}

  if (!title) return

  self.registration.showNotification(title, {
    body: body || '',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    data: { url: url || '/' },
    tag: 'signal-one-alert',
    renotify: true,
  })
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const url = event.notification.data?.url || '/'

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Focus an existing tab if one is open
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url)
          return client.focus()
        }
      }
      // Otherwise open a new tab
      return clients.openWindow(url)
    })
  )
})
`

const outPath = path.resolve(__dirname, '..', 'public', 'firebase-messaging-sw.js')
fs.writeFileSync(outPath, sw)
console.log('Generated public/firebase-messaging-sw.js')

// ─── Caching service worker (public/sw.js) ─────────────────────────────────
// Handles offline fallback and asset caching. Separate from Firebase messaging SW.

const CACHE_VERSION = 'v1'

const cachingSw = `/* eslint-disable no-undef */
// Caching service worker for offline support and asset caching.
// AUTO-GENERATED by scripts/generate-sw.js — do not edit directly.

const CACHE_NAME = 'signal-one-${CACHE_VERSION}'
const OFFLINE_URL = '/offline'

// Precache list — populated at build time
const PRECACHE_URLS = [
  OFFLINE_URL,
  '/icon-192.png',
  '/icon-512.png',
  '/manifest.json',
]

// Install: precache offline page and key assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS))
  )
  self.skipWaiting()
})

// Activate: clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      )
    )
  )
  self.clients.claim()
})

// Fetch: network-first for navigations (fall back to offline page),
// cache-first for static assets, network-only for API calls.
self.addEventListener('fetch', (event) => {
  const { request } = event

  // Skip non-GET requests
  if (request.method !== 'GET') return

  // Skip API routes — real-time data must be fresh
  if (request.url.includes('/api/')) return

  // Skip Firebase messaging SW and external URLs
  if (request.url.includes('firebase-messaging-sw.js')) return
  if (!request.url.startsWith(self.location.origin)) return

  // Navigation requests: network-first, fall back to offline page
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match(OFFLINE_URL))
    )
    return
  }

  // Static assets (JS, CSS, images, fonts): cache-first
  if (
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'image' ||
    request.destination === 'font'
  ) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached
        return fetch(request).then((response) => {
          // Only cache successful responses
          if (!response || response.status !== 200) return response
          const clone = response.clone()
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone))
          return response
        })
      })
    )
    return
  }
})
`

const cachingSwPath = path.resolve(__dirname, '..', 'public', 'sw.js')
fs.writeFileSync(cachingSwPath, cachingSw)
console.log('Generated public/sw.js')
